# Generated by Django 3.1.12 on 2021-06-19 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rendezvous.utils.generate_random_code
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default=rendezvous.utils.generate_random_code.generate_random_code, max_length=15, unique=True)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('scheduled_start_time', models.DateTimeField(default=None, null=True)),
                ('start_time', models.DateTimeField(default=None, null=True)),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_hosted', to=settings.AUTH_USER_MODEL)),
                ('invitees', models.ManyToManyField(blank=True, related_name='meeting_invited_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
