# Generated by Django 3.1.12 on 2021-06-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0002_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('att', 'Attending'), ('ban', 'Banned'), ('lef', 'Left'), ('wai', 'Waiting in Lobby')], default='att', max_length=3),
        ),
    ]
