# Generated by Django 3.1.12 on 2021-07-07 16:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0004_meetingmessage_personalmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('elements', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard', to='rendezvous.meeting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
