MEETING_INFORMATION = 'MEETING_INFORMATION'
PARTICIPANT_LIST = 'PARTICIPANT_LIST'
HOST_JOINED = 'HOST_JOINED'
USER_JOINED = 'USER_JOINED'

ICE_CANDIDATE = 'ICE_CANDIDATE'
PEER_CONNECTION_OFFER = 'PEER_CONNECTION_OFFER'
PEER_CONNECTION_ANSWER = 'PEER_CONNECTION_ANSWER'

generic_message_types = [
    ICE_CANDIDATE, PEER_CONNECTION_ANSWER, PEER_CONNECTION_OFFER
]