// Types of redux actions

// User actions
export const INITIALISE_USER = 'INITIALISE_USER'
export const CHANGE_USER_LOGIN_LOADED_ERROR = 'CHANGE_USER_LOGIN_LOADED_ERROR'

// Meeting actions
export const CHANGE_MEETING_LOADED = 'CHANGE_MEETING_LOADED'
export const UPDATE_MEETING_TITLE_DESCRIPTION = 'UPDATE_MEETING_TITLE_DESCRIPTION'
export const SET_PARTICIPANTS_LIST = 'SET_PARTICIPANTS_LIST'
export const ADD_STREAM = 'ADD_STREAM'
