export const MEETING_INFORMATION = 'MEETING_INFORMATION'
export const USER_JOINED = 'USER_JOINED'
export const USER_LEFT = 'USER_LEFT'
export const PARTICIPANT_LIST = 'PARTICIPANT_LIST'

export const HOST_JOINED = 'HOST_JOINED'
export const PENDING_HOST_JOIN = 'PENDING_HOST_JOIN'
export const PENDING_HOST_PERMISSION = 'PENDING_HOST_PERMISSION'
export const ASK_HOST_PERMISSION_TO_ENTER = 'ASK_HOST_PERMISSION_TO_ENTER'

export const ICE_CANDIDATE = 'ICE_CANDIDATE'
export const PEER_CONNECTION_OFFER = 'PEER_CONNECTION_OFFER'
export const PEER_CONNECTION_ANSWER = 'PEER_CONNECTION_ANSWER'

export const VIDEO_TURNED_OFF = 'VIDEO_TURNED_OFF'
export const AUDIO_TURNED_OFF = 'AUDIO_TURNED_OFF'
export const MEDIA_TURNED_OFF = {
    'video': VIDEO_TURNED_OFF,
    'audio': AUDIO_TURNED_OFF
}

export const ADMIT_USER = 'ADMIT_USER'
export const REJECT_USER = 'REJECT_USER'
export const BAN_USER = 'BAN_USER'
export const REMOVE_USER = 'REMOVE_USER'

export const MESSAGES_LIST = 'MESSAGES_LIST'
export const NEW_MESSAGE = 'NEW_MESSAGE'
export const SEND_MESSAGE = 'SEND_MESSAGE'

export const WHITEBOARD_DRAW_STROKE = 'WHITEBOARD_DRAW_STROKE'
export const INITIALISE_WHITEBOARD = 'INITIALISE_WHITEBOARD'

export const CONVERSATION_CREATE = 'CONVERSATION_CREATE'
export const CONVERSATIONS_LIST = 'CONVERSATIONS_LIST'
export const CONVERSATION_INFO = 'CONVERSATION_INFO'
export const CONVERSATION_MEETING_LIVE = 'CONVERSATION_MEETING_LIVE'

export const websocketMessageTypes = {
    MEETING_INFORMATION,
    USER_JOINED,
    USER_LEFT,
    PARTICIPANT_LIST,

    HOST_JOINED,
    PENDING_HOST_JOIN,
    PENDING_HOST_PERMISSION,
    ASK_HOST_PERMISSION_TO_ENTER,

    ICE_CANDIDATE,
    PEER_CONNECTION_OFFER,
    PEER_CONNECTION_ANSWER,

    VIDEO_TURNED_OFF,
    AUDIO_TURNED_OFF,
    MEDIA_TURNED_OFF,

    ADMIT_USER,
    REJECT_USER,
    BAN_USER,
    REMOVE_USER,

    MESSAGES_LIST,
    NEW_MESSAGE,
    SEND_MESSAGE,

    WHITEBOARD_DRAW_STROKE,
    INITIALISE_WHITEBOARD,

    CONVERSATION_CREATE,
    CONVERSATIONS_LIST,
    CONVERSATION_INFO,
    CONVERSATION_MEETING_LIVE,
}
