export const MEETING_INFORMATION = 'MEETING_INFORMATION'
export const USER_JOINED = 'USER_JOINED'
export const PARTICIPANT_LIST = 'PARTICIPANT_LIST'
export const HOST_JOINED = 'HOST_JOINED'
export const ICE_CANDIDATE = 'ICE_CANDIDATE'
export const PEER_CONNECTION_OFFER = 'PEER_CONNECTION_OFFER'
export const PEER_CONNECTION_ANSWER = 'PEER_CONNECTION_ANSWER'

export const PENDING_HOST_JOIN = 'PENDING_HOST_JOIN'
export const PENDING_HOST_PERMISSION = 'PENDING_HOST_PERMISSION'
export const ASK_HOST_PERMISSION_TO_ENTER = 'ASK_HOST_PERMISSION_TO_ENTER'

export const ADMIT_USER = 'ADMIT_USER'
export const REJECT_USER = 'REJECT_USER'
